#!/usr/bin/python

import os
import sys

import requests


def main():
    refname = sys.argv[1]
    old_commit = sys.argv[2]
    new_commit = sys.argv[3]
    repo_path = os.getcwd()

    payload = {
        'repo_path': repo_path, 
        'refname': refname,
        'old_rev': old_commit, 
        'new_rev': new_commit,
    }
    print('Deploying app...')
    resp = requests.post('http://localhost/app/private/deploy/', data=payload)

    if resp.status_code != 200:
        print(resp.text)
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
